"use client";
import {useEffect,useMemo,useRef,useState} from "react";

type User={matricula:string;name:string;role:"alumno"|"docente"};
type StoredProgress={done?:string[];errorCount?:number;attemptCount?:number;topicErrors?:Record<number,number>;resetAt?:string;topic?:number};
type Quick={q:string;a:string[];hint:string};
type Quiz={q:string;options:string[];a:string;why:string};
type Pair=[string,string];
type Sequence={title:string;steps:string[]};
type Topic={title:string;short:string;icon:string;goal:string;prior:string;route:string[];blocks:{title:string;text:string;formula?:string;points:string[]}[];examples:{p:string;steps:string[];r:string}[];quick:Quick[];quiz:Quiz[];pairs:Pair[];memory:Pair[];sequences:Sequence[];tf:{text:string;answer:boolean;why:string}[]};

const topics:Topic[]=[
 {title:"Ecuaciones de primer grado",short:"Resuelve igualdades lineales y comprueba la solución.",icon:"x",goal:"Resolver ecuaciones lineales con enteros, paréntesis y fracciones, y plantear problemas sencillos.",prior:"Operaciones con signos, jerarquía de operaciones y reducción de términos semejantes.",route:["Concepto y equivalencia","Despeje paso a paso","Paréntesis y fracciones","Comprobación y aplicación"],blocks:[
  {title:"¿Qué es una ecuación?",text:"Una ecuación es una igualdad que contiene una incógnita. Resolverla significa encontrar el valor que hace verdadera la igualdad.",formula:"ax+b=c, con a≠0",points:["Los dos miembros están separados por el signo =.","Una operación aplicada en un miembro debe aplicarse también en el otro.","La solución se comprueba sustituyendo el valor obtenido."]},
  {title:"Principio de equivalencia",text:"Sumar, restar, multiplicar o dividir ambos miembros por la misma cantidad no altera la solución; nunca se divide entre cero.",formula:"a=b ⇒ a+c=b+c",points:["Reduce términos semejantes antes de despejar.","Elimina paréntesis respetando signos.","Usa el mínimo común múltiplo cuando existan fracciones."]},
  {title:"Casos especiales",text:"Si al simplificar resulta 0=0, todos los números reales son solución. Si resulta una igualdad falsa como 0=5, no existe solución.",points:["Identidad: infinitas soluciones.","Contradicción: conjunto solución vacío.","Ecuación determinada: una solución."]}
 ],examples:[
  {p:"Resolver x+2=5",steps:["Resta 2 en ambos miembros: x+2−2=5−2.","Simplifica: x=3.","Comprueba: 3+2=5."],r:"x=3"},
  {p:"Resolver 8x−6=6x+4",steps:["Resta 6x: 2x−6=4.","Suma 6: 2x=10.","Divide entre 2: x=5."],r:"x=5"},
  {p:"Resolver 3·(x−2)+5=2x+7",steps:["Distribuye: 3x−6+5=2x+7.","Simplifica: 3x−1=2x+7.","Resta 2x y suma 1: x=8."],r:"x=8"},
  {p:"Resolver x/2+x/3=10",steps:["El m.c.m. de 2 y 3 es 6.","Multiplica toda la ecuación por 6: 3x+2x=60.","5x=60; divide entre 5."],r:"x=12"}
 ],quick:[
  {q:"x+2=5",a:["3","x=3"],hint:"Resta 2 en ambos miembros."},{q:"2x−3=5",a:["4","x=4"],hint:"Suma 3 y divide entre 2."},{q:"3y+2=11",a:["3","y=3"],hint:"Resta 2 antes de dividir entre 3."},{q:"8x−6=6x+4",a:["5","x=5"],hint:"Reúne los términos con x en un miembro."},{q:"3−z=9",a:["-6","z=-6"],hint:"Resta 3: −z=6; después cambia el signo."},{q:"3·(x−2)+5=2x+7",a:["8","x=8"],hint:"Aplica primero la propiedad distributiva."}
 ],quiz:[
  {q:"¿Cuál operación conserva la equivalencia de x−7=4?",options:["Sumar 7 a ambos miembros","Sumar 7 solo al miembro izquierdo","Multiplicar solo el derecho por 7","Cambiar el signo = por >"],a:"Sumar 7 a ambos miembros",why:"La misma operación debe aplicarse en ambos miembros."},
  {q:"La solución de 5x+7=2 es:",options:["x=−1","x=1","x=−5","x=5"],a:"x=−1",why:"5x=−5 y x=−1."},
  {q:"Si al simplificar una ecuación resulta 0=0, entonces:",options:["Tiene infinitas soluciones","No tiene solución","La solución es 0","La solución es 1"],a:"Tiene infinitas soluciones",why:"La igualdad es verdadera para cualquier valor."},
  {q:"¿Qué se hace primero en 4·(x+3)=20?",options:["Aplicar la distributiva o dividir ambos miembros entre 4","Restar 3 solo a la izquierda","Multiplicar por 20","Cambiar x por 4"],a:"Aplicar la distributiva o dividir ambos miembros entre 4",why:"Ambos caminos producen una ecuación equivalente."},
  {q:"Un servicio cobra $80 de cuota y $25 por hora. Si se pagaron $205, ¿qué ecuación modela las horas h?",options:["80+25h=205","80h+25=205","25+h=205","205h=105"],a:"80+25h=205",why:"El total es cuota fija más costo por hora."},
  {q:"La comprobación de x=6 en 2x+1=13 es:",options:["2·6+1=13","2+6·1=13","2·13+1=6","6+1=13"],a:"2·6+1=13",why:"Se sustituye la incógnita por el valor obtenido."}
 ],pairs:[["Incógnita","Valor desconocido representado por una letra"],["Miembro","Expresión ubicada a un lado del signo igual"],["Solución","Valor que hace verdadera la igualdad"],["Identidad","Ecuación verdadera para todos los valores permitidos"],["Contradicción","Ecuación que conduce a una igualdad falsa"],["Comprobación","Sustitución de la solución en la ecuación original"]],memory:[["x+4=9","x=5"],["2x=14","x=7"],["3x−1=8","x=3"],["10−x=6","x=4"],["5x+5=0","x=−1"],["x/3=4","x=12"]],sequences:[
  {title:"Resolver 2x−3=5",steps:["Sumar 3 en ambos miembros","Obtener 2x=8","Dividir entre 2 y concluir x=4"]},{title:"Resolver 4·(x+2)=20",steps:["Dividir ambos miembros entre 4","Obtener x+2=5","Restar 2 y concluir x=3"]},{title:"Resolver 3x+2=x+10",steps:["Restar x en ambos miembros","Obtener 2x+2=10","Restar 2, dividir entre 2 y obtener x=4"]},{title:"Resolver x/2+x/3=10",steps:["Identificar que el m.c.m. es 6","Multiplicar toda la ecuación por 6","Resolver 3x+2x=60 y obtener x=12"]},{title:"Comprobar x=−1 en 5x+7=2",steps:["Sustituir x por −1","Calcular 5·(−1)+7","Verificar que 2=2"]},{title:"Modelar cuota de $80 más $25 por hora",steps:["Definir h como número de horas","Escribir 80+25h","Igualar al total pagado"]}
 ],tf:[
  {text:"En una ecuación puede sumarse la misma cantidad en ambos miembros.",answer:true,why:"Es una transformación equivalente."},{text:"En 2x=10, la solución es x=20.",answer:false,why:"Se divide entre 2: x=5."},{text:"Una solución debe hacer verdadera la igualdad original.",answer:true,why:"La sustitución permite comprobarla."},{text:"Si se obtiene 0=7, todos los reales son solución.",answer:false,why:"0=7 es falso; no existe solución."},{text:"Para eliminar denominadores puede multiplicarse toda la ecuación por el m.c.m.",answer:true,why:"Debe multiplicarse cada término de ambos miembros."},{text:"3·(x+2)=3x+2.",answer:false,why:"La distributiva produce 3x+6."}
 ]},
 {title:"Desigualdades lineales",short:"Determina conjuntos solución y represéntalos mediante intervalos.",icon:"<",goal:"Resolver desigualdades simples y compuestas, escribir intervalos y representar la solución en la recta numérica.",prior:"Orden de los números reales, operaciones con signos y resolución de ecuaciones lineales.",route:["Símbolos y propiedades","Cambio de sentido","Intervalos","Desigualdades compuestas"],blocks:[
  {title:"Desigualdad e inecuación",text:"Una desigualdad compara dos expresiones con <, >, ≤ o ≥. Su solución suele ser un conjunto de valores, no un único número.",formula:"ax+b<c",points:["< y > no incluyen el extremo.","≤ y ≥ sí incluyen el extremo.","La solución puede escribirse como desigualdad, intervalo y gráfica."]},
  {title:"Regla esencial",text:"Al multiplicar o dividir todos los miembros por un número negativo, el sentido de la desigualdad se invierte.",formula:"−2x>6 ⇒ x<−3",points:["Sumar o restar no cambia el sentido.","Multiplicar por un positivo no cambia el sentido.","Multiplicar por un negativo sí lo cambia."]},
  {title:"Notación de intervalos",text:"Los paréntesis indican extremo no incluido y los corchetes extremo incluido. Con infinito siempre se utiliza paréntesis.",formula:"x≥3 ⇔ [3,∞)",points:["x<a se escribe (−∞,a).","x≤a se escribe (−∞,a].","a<x≤b se escribe (a,b]."]}
 ],examples:[
  {p:"Resolver 12x−4>7x+11",steps:["Resta 7x: 5x−4>11.","Suma 4: 5x>15.","Divide entre 5."],r:"x>3; intervalo (3,∞)"},
  {p:"Resolver −3x≥27",steps:["Divide entre −3.","Invierte ≥ porque divides por un negativo.","Representa con punto cerrado en −9."],r:"x≤−9; intervalo (−∞,−9]"},
  {p:"Resolver −7<4x+1<13",steps:["Resta 1 en los tres miembros: −8<4x<12.","Divide entre 4: −2<x<3.","Usa paréntesis porque los extremos no se incluyen."],r:"(−2,3)"}
 ],quick:[
  {q:"12x−4>7x+11",a:["x>3","(3,∞)","(3,infinito)"],hint:"Reúne las x y después divide entre 5."},{q:"3x+9>7x−3",a:["x<3","(-∞,3)","(-infinito,3)"],hint:"Al final dividirás entre un número negativo."},{q:"2x−5<x−9",a:["x<-4","(-∞,-4)","(-infinito,-4)"],hint:"Resta x y suma 5."},{q:"4x−2≥12x+6",a:["x≤-1","(-∞,-1]","(-infinito,-1]"],hint:"Obtendrás −8x≥8; invierte el signo al dividir."},{q:"−7<4x+1<13",a:["-2<x<3","(-2,3)"],hint:"Opera en los tres miembros."},{q:"−6<2x−3<4",a:["-1.5<x<3.5","-3/2<x<7/2","(-3/2,7/2)"],hint:"Suma 3 y divide los tres miembros entre 2."}
 ],quiz:[
  {q:"¿Cuándo debe invertirse el signo de desigualdad?",options:["Al multiplicar o dividir por un número negativo","Al sumar un positivo","Al restar el mismo número","Al dividir por un positivo"],a:"Al multiplicar o dividir por un número negativo",why:"Esa operación invierte el orden."},
  {q:"¿Qué intervalo representa x≤4?",options:["(−∞,4]","(−∞,4)","[4,∞)","(4,∞)"],a:"(−∞,4]",why:"Incluye 4 y todos los menores."},
  {q:"En la gráfica de x>−2, el punto en −2 debe ser:",options:["Abierto","Cerrado","Doble","Inexistente"],a:"Abierto",why:"El signo > no incluye el extremo."},
  {q:"La solución de −2x<8 es:",options:["x>−4","x<−4","x>4","x<4"],a:"x>−4",why:"Al dividir entre −2 se invierte < a >."},
  {q:"Un archivo debe pesar como máximo 10 MB. Si p es su peso, se escribe:",options:["p≤10","p<10","p≥10","p=10"],a:"p≤10",why:"Como máximo incluye 10 y valores menores."},
  {q:"¿Qué intervalo corresponde a −1≤x<5?",options:["[−1,5)","(−1,5]","[−1,5]","(−1,5)"],a:"[−1,5)",why:"Incluye −1, pero no incluye 5."}
 ],pairs:[["x<3","(−∞,3)"],["x≤3","(−∞,3]"],["x>3","(3,∞)"],["x≥3","[3,∞)"],["−2<x≤4","(−2,4]"],["1≤x<7","[1,7)"]],memory:[["Punto abierto","Extremo no incluido"],["Punto cerrado","Extremo incluido"],["x≥0","[0,∞)"],["x<−1","(−∞,−1)"],["Dividir entre −5","Invertir el signo"],["Sumar el mismo número","Conservar el signo"]],sequences:[
  {title:"Resolver 2x−1>7",steps:["Sumar 1 en ambos miembros","Obtener 2x>8","Dividir entre 2 y concluir x>4"]},{title:"Resolver −3x≤12",steps:["Dividir ambos miembros entre −3","Invertir el signo ≤ a ≥","Concluir x≥−4"]},{title:"Representar x≤2",steps:["Ubicar 2 en la recta","Marcar un punto cerrado","Sombrear hacia la izquierda"]},{title:"Escribir el intervalo de x>5",steps:["Reconocer que 5 no está incluido","Usar paréntesis en 5","Escribir (5,∞)"]},{title:"Resolver −7<4x+1<13",steps:["Restar 1 en los tres miembros","Dividir los tres miembros entre 4","Concluir −2<x<3"]},{title:"Modelar una capacidad máxima de 30",steps:["Definir c como cantidad utilizada","Interpretar que 30 sí se permite","Escribir c≤30"]}
 ],tf:[
  {text:"Al sumar el mismo número en ambos miembros, el signo no cambia.",answer:true,why:"La suma conserva el orden."},{text:"Al dividir una desigualdad entre −4, el signo conserva su dirección.",answer:false,why:"Debe invertirse."},{text:"El intervalo [2,∞) incluye el número 2.",answer:true,why:"El corchete incluye el extremo."},{text:"El infinito puede escribirse con corchete.",answer:false,why:"El infinito nunca es un extremo alcanzable."},{text:"x<5 se representa con punto abierto en 5.",answer:true,why:"El 5 no pertenece a la solución."},{text:"−2≤x<3 se escribe (−2,3].",answer:false,why:"Se escribe [−2,3)."}
 ]},
 {title:"Sistemas de ecuaciones lineales",short:"Encuentra valores que satisfacen simultáneamente dos ecuaciones.",icon:"{",goal:"Resolver sistemas 2×2 mediante reducción, sustitución e igualación, y verificar la pareja solución.",prior:"Despeje, operaciones con ecuaciones lineales y pares ordenados.",route:["Solución común","Método de reducción","Sustitución e igualación","Comprobación y aplicación"],blocks:[
  {title:"¿Qué es un sistema 2×2?",text:"Es un conjunto de dos ecuaciones lineales con dos incógnitas. La solución es el par ordenado que satisface ambas ecuaciones.",formula:"{ ax+by=c; dx+ey=f }",points:["Una solución: las rectas se cortan.","Ninguna solución: rectas paralelas.","Infinitas soluciones: la misma recta."]},
  {title:"Reducción",text:"Se multiplican una o ambas ecuaciones para obtener coeficientes opuestos y eliminar una incógnita al sumar.",points:["Alinea términos semejantes.","Elimina una variable.","Sustituye el valor para obtener la otra."]},
  {title:"Sustitución e igualación",text:"En sustitución se despeja una variable y se reemplaza en la otra ecuación. En igualación se despeja la misma variable en ambas ecuaciones y se igualan las expresiones.",points:["Elige el método que produzca cálculos más simples.","La respuesta siempre debe expresarse como (x,y).","Comprueba en las dos ecuaciones originales."]}
 ],examples:[
  {p:"Resolver {x+y=4; x−y=2} por reducción",steps:["Suma las ecuaciones: 2x=6.","Obtén x=3.","Sustituye en x+y=4: y=1."],r:"(x,y)=(3,1)"},
  {p:"Resolver {x+y=7; 2x−y=2}",steps:["Suma: 3x=9.","x=3.","Sustituye: 3+y=7, entonces y=4."],r:"(3,4)"},
  {p:"Dos boletos cuestan $160; adulto $100 y estudiante $60",steps:["Define x adultos y y estudiantes.","Cantidad: x+y=2; costo: 100x+60y=160.","Resuelve el sistema."],r:"x=1, y=1"}
 ],quick:[
  {q:"{x+y=4; x−y=2}",a:["(3,1)","x=3,y=1","3,1"],hint:"Suma ambas ecuaciones para eliminar y."},{q:"{x+y=7; 2x−y=2}",a:["(3,4)","x=3,y=4","3,4"],hint:"Suma las ecuaciones."},{q:"{2x+y=8; x−y=1}",a:["(3,2)","x=3,y=2","3,2"],hint:"Suma para obtener 3x=9."},{q:"{3x−2y=0; x−y=−1}",a:["(2,3)","x=2,y=3","2,3"],hint:"Multiplica la segunda ecuación por −2 o despeja x."},{q:"{5x−2y=2; 7x+6y=38}",a:["(2,4)","x=2,y=4","2,4"],hint:"Multiplica la primera ecuación por 3."},{q:"{x+2y=5; 3x−2y=7}",a:["(3,1)","x=3,y=1","3,1"],hint:"Suma las ecuaciones para eliminar y."}
 ],quiz:[
  {q:"La solución de un sistema 2×2 es:",options:["Un par ordenado que satisface ambas ecuaciones","Cualquier valor de x","Solo el valor de y","El resultado de sumar coeficientes"],a:"Un par ordenado que satisface ambas ecuaciones",why:"Debe cumplir simultáneamente las dos igualdades."},
  {q:"¿Qué método busca coeficientes opuestos?",options:["Reducción","Sustitución","Factorización","Fórmula general"],a:"Reducción",why:"Al sumar, una incógnita se elimina."},
  {q:"Si dos rectas son paralelas distintas, el sistema tiene:",options:["Ninguna solución","Una solución","Dos soluciones","Infinitas soluciones"],a:"Ninguna solución",why:"Las rectas no se intersectan."},
  {q:"En sustitución, después de despejar x se debe:",options:["Reemplazarla en la otra ecuación","Cambiar ambos signos","Multiplicar siempre por −1","Aplicar fórmula general"],a:"Reemplazarla en la otra ecuación",why:"Así queda una ecuación con una sola incógnita."},
  {q:"Para comprobar (2,3) en un sistema se debe:",options:["Sustituir x=2, y=3 en ambas ecuaciones","Comprobar solo la primera","Sumar 2+3","Intercambiar los valores"],a:"Sustituir x=2, y=3 en ambas ecuaciones",why:"La pareja debe satisfacer las dos."},
  {q:"Dos planes suman 30 usuarios y cuestan en total $2400. ¿Qué representa el sistema?",options:["Dos condiciones simultáneas","Una desigualdad","Una identidad","Una ecuación cuadrática"],a:"Dos condiciones simultáneas",why:"Cantidad y costo deben cumplirse a la vez."}
 ],pairs:[["Reducción","Eliminar una variable mediante suma de ecuaciones"],["Sustitución","Reemplazar un despeje en la otra ecuación"],["Igualación","Igualar dos expresiones de la misma variable"],["Solución única","Rectas que se cortan en un punto"],["Sin solución","Rectas paralelas distintas"],["Infinitas soluciones","Ecuaciones que representan la misma recta"]],memory:[["{x+y=4; x−y=2}","(3,1)"],["{x+y=7; 2x−y=2}","(3,4)"],["{2x+y=8; x−y=1}","(3,2)"],["Par ordenado","(x,y)"],["Rectas paralelas","Sin solución"],["Rectas coincidentes","Infinitas soluciones"]],sequences:[
  {title:"Reducción en {x+y=4; x−y=2}",steps:["Sumar las dos ecuaciones","Resolver 2x=6","Sustituir x=3 y obtener y=1"]},{title:"Sustitución",steps:["Despejar una incógnita","Sustituir el despeje en la otra ecuación","Resolver y regresar al despeje"]},{title:"Igualación",steps:["Despejar la misma incógnita en ambas ecuaciones","Igualar las dos expresiones","Resolver y sustituir para hallar la otra variable"]},{title:"Comprobar una pareja",steps:["Sustituir x e y en la primera ecuación","Verificar la primera igualdad","Sustituir y verificar también la segunda"]},{title:"Modelar un problema",steps:["Definir las dos incógnitas","Traducir las dos condiciones a ecuaciones","Resolver y explicar la pareja en el contexto"]},{title:"Detectar sistema sin solución",steps:["Reducir el sistema","Obtener una igualdad falsa como 0=5","Concluir que las rectas son paralelas"]}
 ],tf:[
  {text:"La solución de un sistema debe satisfacer las dos ecuaciones.",answer:true,why:"Es una solución simultánea."},{text:"El método de reducción siempre elimina x.",answer:false,why:"Puede eliminarse x o y."},{text:"Dos rectas paralelas distintas forman un sistema sin solución.",answer:true,why:"No tienen punto común."},{text:"En sustitución no es necesario regresar al despeje.",answer:false,why:"Se necesita hallar la segunda incógnita."},{text:"La solución (3,1) se interpreta como x=3 y y=1.",answer:true,why:"Ese es el orden del par."},{text:"Comprobar solo una ecuación es suficiente.",answer:false,why:"La pareja debe verificar ambas."}
 ]},
 {title:"Ecuaciones de segundo grado",short:"Calcula raíces mediante factorización, completar el cuadrado y fórmula general.",icon:"x²",goal:"Reconocer ecuaciones cuadráticas, resolverlas con métodos adecuados e interpretar el discriminante.",prior:"Productos notables, factorización, potencias, radicales y ecuaciones lineales.",route:["Forma general","Factorización","Fórmula general","Discriminante y aplicación"],blocks:[
  {title:"Forma general",text:"Una ecuación de segundo grado tiene la forma ax²+bx+c=0, con a distinto de cero. Puede tener dos, una o ninguna raíz real.",formula:"ax²+bx+c=0, a≠0",points:["Ordena la ecuación antes de identificar a, b y c.","Una ecuación incompleta puede tener b=0 o c=0.","Las soluciones también se llaman raíces."]},
  {title:"Métodos de solución",text:"Si el trinomio se factoriza fácilmente, aplica el producto cero. Para cualquier cuadrática puede emplearse la fórmula general.",formula:"x=(−b±√(b²−4ac))/(2a)",points:["Factorización: cada factor se iguala a cero.","Completar el cuadrado transforma el miembro en un binomio al cuadrado.","La fórmula general requiere sustituir signos con cuidado."]},
  {title:"Discriminante",text:"El valor Δ=b²−4ac anticipa el tipo de raíces reales.",formula:"Δ>0: dos; Δ=0: una doble; Δ<0: ninguna real",points:["Calcula primero Δ.","No confundas −b con b.","Comprueba las raíces en la ecuación original."]}
 ],examples:[
  {p:"Resolver x²+5x+4=0",steps:["Busca dos números que sumen 5 y multipliquen 4.","Factoriza: (x+1)·(x+4)=0.","Iguala cada factor a cero."],r:"x=−1 o x=−4"},
  {p:"Resolver 2x²−3x=0",steps:["Extrae factor común x.","x·(2x−3)=0.","Aplica producto cero."],r:"x=0 o x=3/2"},
  {p:"Resolver x²−6x−27=0",steps:["a=1, b=−6, c=−27.","Δ=(−6)²−4·1·(−27)=144.","x=(6±12)/2."],r:"x=9 o x=−3"},
  {p:"Altura h(t)=−5t²+20t; hallar cuándo vuelve al suelo",steps:["Iguala h(t)=0.","Factoriza: −5t·(t−4)=0.","Interpreta t=0 como inicio y t=4 como regreso."],r:"Vuelve al suelo a los 4 s"}
 ],quick:[
  {q:"x²+5x+4=0",a:["-1,-4","-4,-1","x=-1,x=-4","x=-4,x=-1"],hint:"Factoriza con números que sumen 5 y multipliquen 4."},{q:"x²+11x+30=0",a:["-5,-6","-6,-5","x=-5,x=-6","x=-6,x=-5"],hint:"Busca factores de 30 cuya suma sea 11."},{q:"x²−10x+24=0",a:["4,6","6,4","x=4,x=6","x=6,x=4"],hint:"Busca dos números positivos que sumen 10."},{q:"2x²−3x=0",a:["0,3/2","3/2,0","0,1.5","1.5,0"],hint:"Extrae factor común x."},{q:"x²−6x−27=0",a:["9,-3","-3,9","x=9,x=-3","x=-3,x=9"],hint:"Puedes factorizar o usar la fórmula general."},{q:"x²+4x+4=0",a:["-2","x=-2","-2,-2"],hint:"Es un trinomio cuadrado perfecto."}
 ],quiz:[
  {q:"En 3x²−5x+2=0, los coeficientes son:",options:["a=3, b=−5, c=2","a=−5, b=3, c=2","a=3, b=5, c=−2","a=2, b=−5, c=3"],a:"a=3, b=−5, c=2",why:"Se leen respetando sus signos."},
  {q:"Si Δ>0, la ecuación tiene:",options:["Dos raíces reales distintas","Una raíz real doble","Ninguna raíz real","Infinitas raíces"],a:"Dos raíces reales distintas",why:"La raíz del discriminante produce dos valores."},
  {q:"¿Qué propiedad se aplica a (x−2)·(x+3)=0?",options:["Producto cero","Propiedad distributiva","Regla de tres","Cambio de sentido"],a:"Producto cero",why:"Al menos uno de los factores debe valer cero."},
  {q:"El discriminante de x²+4x+4=0 es:",options:["0","4","8","16"],a:"0",why:"16−16=0."},
  {q:"¿Cuál ecuación es de segundo grado?",options:["2x²−3x+1=0","2x−3=0","x³−1=0","1/x=2"],a:"2x²−3x+1=0",why:"Su mayor exponente es 2 y a≠0."},
  {q:"En un problema de altura, una raíz t=0 suele representar:",options:["El instante inicial","La altura máxima","Una respuesta imposible siempre","El discriminante"],a:"El instante inicial",why:"El objeto parte del suelo en t=0."}
 ],pairs:[["a","Coeficiente de x²"],["b","Coeficiente de x"],["c","Término independiente"],["Δ>0","Dos raíces reales distintas"],["Δ=0","Una raíz real doble"],["Δ<0","No hay raíces reales"]],memory:[["x²−9=0","x=−3, 3"],["x²−5x+6=0","x=2, 3"],["x²+4x+4=0","x=−2"],["2x²−8=0","x=−2, 2"],["Δ=b²−4ac","Discriminante"],["ax²+bx+c=0","Forma general"]],sequences:[
  {title:"Resolver por factorización",steps:["Escribir la ecuación igualada a cero","Factorizar el polinomio","Igualar cada factor a cero"]},{title:"Usar fórmula general",steps:["Identificar a, b y c con sus signos","Calcular el discriminante","Sustituir y calcular las dos posibilidades"]},{title:"Resolver 2x²−3x=0",steps:["Extraer el factor común x","Escribir x·(2x−3)=0","Concluir x=0 o x=3/2"]},{title:"Analizar el discriminante",steps:["Calcular b²−4ac","Comparar el resultado con cero","Determinar el número de raíces reales"]},{title:"Comprobar una raíz",steps:["Sustituir x en la ecuación original","Realizar potencias y productos","Verificar que el resultado sea cero"]},{title:"Resolver un problema cuadrático",steps:["Definir la incógnita y formular la ecuación","Resolver la ecuación cuadrática","Interpretar y descartar valores sin sentido físico"]}
 ],tf:[
  {text:"En ax²+bx+c=0, el coeficiente a no puede ser cero.",answer:true,why:"Si a=0, la ecuación deja de ser cuadrática."},{text:"Una ecuación cuadrática siempre tiene dos raíces reales distintas.",answer:false,why:"Depende del discriminante."},{text:"Si Δ=0 existe una raíz real doble.",answer:true,why:"Las dos expresiones de la fórmula coinciden."},{text:"x²−9 se factoriza como (x−3)·(x+3).",answer:true,why:"Es una diferencia de cuadrados."},{text:"En la fórmula general puede ignorarse el signo de b.",answer:false,why:"Los signos determinan el resultado."},{text:"Las raíces deben comprobarse en la ecuación original.",answer:true,why:"La sustitución confirma la solución."}
 ]}
];

const modules={quick:["1","Respuesta abierta"],quiz:["2","Opción múltiple"],match:["3","Relacionar"],memory:["4","Memoria"],sequence:["5","Ordenar pasos"],tf:["6","Verdadero/Falso"]} as const;
type ModuleKey=keyof typeof modules;
const clean=(v:string)=>v.toLowerCase().replace(/\s+/g,"").replaceAll("−","-").replaceAll("∞","infinito").replace(/[{}]/g,"");
function shuffle<T>(items:T[],seed:number){const a=[...items];let s=seed+1;for(let i=a.length-1;i>0;i--){s=(s*9301+49297)%233280;const j=Math.floor(s/233280*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function MathText({text}:{text:string}){const parts=text.split(/(-?\d+)\/(-?\d+)/g);return <>{parts.map((part,i)=>i%3===1?<span className="frac" key={i}><span>{part}</span><span>{parts[i+1]}</span></span>:i%3===2?null:<span key={i}>{part}</span>)}</>}

export default function Home(){
 const[user,setUser]=useState<User|null>(null),[authReady,setAuthReady]=useState(false),[authMode,setAuthMode]=useState<"login"|"register">("login"),[authBusy,setAuthBusy]=useState(false),[authError,setAuthError]=useState(""),[groups,setGroups]=useState<{id:string;nombre:string}[]>([]),[form,setForm]=useState({matricula:"",password:"",name:"",groupId:""});
 const[ti,setTi]=useState(0),[tab,setTab]=useState<ModuleKey>("quick"),[done,setDone]=useState<string[]>([]),[errors,setErrors]=useState(0),[attempts,setAttempts]=useState(0),[topicErrors,setTopicErrors]=useState<Record<number,number>>({}),[round,setRound]=useState(0),[reviewErrors,setReviewErrors]=useState(0),[note,setNote]=useState("");
 const[input,setInput]=useState(""),[quickIndex,setQuickIndex]=useState(0),[quickSolved,setQuickSolved]=useState(0),[quizAnswers,setQuizAnswers]=useState<Record<number,string>>({}),[matchAnswers,setMatchAnswers]=useState<Record<number,string>>({}),[opened,setOpened]=useState<number[]>([]),[matched,setMatched]=useState<number[]>([]),[seqIndex,setSeqIndex]=useState(0),[seqPick,setSeqPick]=useState<string[]>([]),[tfAnswers,setTfAnswers]=useState<Record<number,boolean>>({});
 const resetAt=useRef("");const t=topics[ti];
 const quick=useMemo(()=>shuffle(t.quick,ti*101+round*17).slice(0,5),[t,ti,round]);
 const quiz=useMemo(()=>shuffle(t.quiz,ti*103+round*19).slice(0,5),[t,ti,round]);
 const pairs=useMemo(()=>shuffle(t.pairs,ti*107+round*23).slice(0,5),[t,ti,round]);
 const matchOptions=useMemo(()=>shuffle(pairs.map(x=>x[1]),ti*109+round*29),[pairs,ti,round]);
 const memoryPairs=useMemo(()=>shuffle(t.memory,ti*113+round*31).slice(0,5),[t,ti,round]);
 const cards=useMemo(()=>shuffle(memoryPairs.flatMap((p,pair)=>p.map(text=>({text,pair}))),ti*127+round*37),[memoryPairs,ti,round]);
 const sequences=useMemo(()=>shuffle(t.sequences,ti*131+round*41).slice(0,5),[t,ti,round]);
 const tfItems=useMemo(()=>shuffle(t.tf,ti*137+round*43).slice(0,5),[t,ti,round]);
 const progress=Math.round(done.length/24*100);
 const mark=(key:ModuleKey)=>setDone(v=>v.includes(`${ti}-${key}`)?v:[...v,`${ti}-${key}`]);
 const addResult=(total:number,wrong:number)=>{setAttempts(v=>v+total);if(wrong){setErrors(v=>v+wrong);setReviewErrors(v=>v+wrong);setTopicErrors(v=>({...v,[ti]:(v[ti]||0)+wrong}))}};
 const resetModule=()=>{setInput("");setQuickIndex(0);setQuickSolved(0);setQuizAnswers({});setMatchAnswers({});setOpened([]);setMatched([]);setSeqIndex(0);setSeqPick([]);setTfAnswers({});setReviewErrors(0);setNote("")};
 const openTopic=(i:number)=>{setTi(i);setTab("quick");setRound(0);resetModule()};
 const applyProgress=(p:StoredProgress)=>{setDone(p?.done||[]);setErrors(Number(p?.errorCount)||0);setAttempts(Number(p?.attemptCount)||0);setTopicErrors(p?.topicErrors||{});resetAt.current=typeof p?.resetAt==="string"?p.resetAt:"";setTi(Number.isInteger(p?.topic)?Number(p.topic):0)};
 async function persist(){if(!user)return;const r=await fetch("/api/student",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({progress:{done,topic:ti,errorCount:errors,attemptCount:attempts,topicErrors,resetAt:resetAt.current||undefined,updatedAt:Date.now()}})});if(r.status===409){const d=await r.json();applyProgress(d.progress||{});resetModule();window.alert("Tu docente reinició el progreso de la Unidad II. El intento anterior quedó archivado.")}}
 useEffect(()=>{fetch("/api/student").then(async r=>{if(r.ok){const d=await r.json();setUser(d.user);applyProgress(d.progress||{})}}).finally(()=>setAuthReady(true));fetch("/api/groups").then(r=>r.ok?r.json():{groups:[]}).then(d=>setGroups(d.groups||[]))},[]);
 useEffect(()=>{if(!user)return;const id=setTimeout(()=>{void persist()},500);return()=>clearTimeout(id)},[done,ti,errors,attempts,topicErrors,user]);
 useEffect(()=>{if(!user)return;let timer:ReturnType<typeof setTimeout>;const renew=()=>{clearTimeout(timer);timer=setTimeout(()=>{void logout(true)},30*60*1000)};const events=["pointerdown","pointermove","keydown","scroll","touchstart"] as const;events.forEach(e=>window.addEventListener(e,renew,{passive:true}));renew();return()=>{clearTimeout(timer);events.forEach(e=>window.removeEventListener(e,renew))}},[user]);
 async function submitAuth(e:React.FormEvent){e.preventDefault();setAuthBusy(true);setAuthError("");const r=await fetch("/api/student",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:authMode,...form})});const d=await r.json();if(!r.ok){setAuthBusy(false);setAuthError(d.error||"No fue posible ingresar.");return}const saved=await fetch("/api/student");if(saved.ok){const p=await saved.json();applyProgress(p.progress||{})}setUser(d.user);setAuthBusy(false)}
 async function logout(idle=false){await persist();await fetch("/api/student",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})});setUser(null);if(idle)window.alert("La sesión se cerró después de 30 minutos de inactividad. Tu progreso quedó guardado.")}
 function checkQuick(){const q=quick[quickIndex],ok=q.a.some(a=>clean(a)===clean(input));addResult(1,ok?0:1);if(!ok){setNote(`Aún no. Pista: ${q.hint}`);return}const n=quickSolved+1;setQuickSolved(n);setInput("");setNote("¡Correcto! Continúa con el siguiente ejercicio.");if(n===5)mark("quick");else setQuickIndex(i=>i+1)}
 function retry(message:string){setRound(v=>v+1);setQuizAnswers({});setMatchAnswers({});setTfAnswers({});setNote(message)}
 function checkQuiz(){if(Object.keys(quizAnswers).length<5){setNote("Responde las cinco preguntas antes de corroborar.");return}const wrong=quiz.filter((q,i)=>quizAnswers[i]!==q.a).length;addResult(5,wrong);if(!wrong){mark("quiz");setNote("¡Correcto! Las cinco respuestas fueron comprobadas.")}else retry(`Hay ${wrong} respuestas por revisar. Lee nuevamente cada enunciado.`)}
 function checkMatch(){if(Object.keys(matchAnswers).length<5){setNote("Completa las cinco relaciones antes de corroborar.");return}const wrong=pairs.filter((p,i)=>matchAnswers[i]!==p[1]).length;addResult(5,wrong);if(!wrong){mark("match");setNote("¡Correcto! Las relaciones son adecuadas.")}else retry(`Hay ${wrong} relaciones por revisar. Analiza nuevamente los conceptos.`)}
 function flip(i:number){if(opened.length===2||opened.includes(i)||matched.includes(cards[i].pair))return;const next=[...opened,i];setOpened(next);if(next.length===2)setTimeout(()=>{const ok=cards[next[0]].pair===cards[next[1]].pair;addResult(1,ok?0:1);if(ok){const m=[...matched,cards[next[0]].pair];setMatched(m);if(m.length===5)mark("memory")}setOpened([])},700)}
 function checkSequence(){const seq=sequences[seqIndex];if(seqPick.length<3){setNote("Selecciona los tres pasos antes de corroborar.");return}const wrong=seq.steps.filter((s,i)=>seqPick[i]!==s).length;addResult(3,wrong);if(wrong){setSeqPick([]);setRound(v=>v+1);setNote("El orden todavía no es correcto. Identifica qué debe ocurrir primero.");return}if(seqIndex===4){mark("sequence");setNote("¡Correcto! Completaste los cinco procedimientos.")}else{setSeqIndex(i=>i+1);setSeqPick([]);setNote("¡Correcto! Continúa con el siguiente procedimiento.")}}
 function checkTf(){if(Object.keys(tfAnswers).length<5){setNote("Responde los cinco enunciados antes de corroborar.");return}const wrong=tfItems.filter((q,i)=>tfAnswers[i]!==q.answer).length;addResult(5,wrong);if(!wrong){mark("tf");setNote("¡Correcto! Los cinco enunciados fueron comprobados.")}else retry(`Hay ${wrong} enunciados por revisar. Justifica cada decisión con la teoría.`)}
 return <main className="u1-site u2-site">
  <header className="site-header"><a className="logo" href="#inicio"><img className="logo-image" src="/brand-icon-fm.svg" alt="Monograma FM"/><span>Fundamentos <span>Matemáticos</span></span></a><nav className="top-nav"><a href="#inicio">1. Introducción</a><a href="#practica">2. Módulos interactivos</a>{user?.role==="docente"&&<a href="/docente">Zona Docente</a>}</nav><div className="header-student">{user?<><span><b>{user.name}</b><small>{user.role==="docente"?"DOCENTE":"ALUMNO"} · {user.matricula}</small></span><button onClick={()=>logout(false)}>Salir</button></>:<button onClick={()=>setAuthReady(true)}>Ingresar</button>}</div></header>
  {!user&&authReady&&<div className="auth-overlay"><section className="auth-card"><img src="/brand-icon-fm.svg" alt="Monograma FM"/><span className="kicker"><i/> Progreso independiente</span><h2>{authMode==="login"?"Continúa con la Unidad II":"Crea tu cuenta de alumno"}</h2><p>Si ya utilizaste la Unidad I, ingresa con la misma matrícula y contraseña. Tu avance de ambas unidades permanecerá separado.</p><form onSubmit={submitAuth}>{authMode==="register"&&<><label>Nombre completo<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Grupo<select value={form.groupId} onChange={e=>setForm({...form,groupId:e.target.value})} required><option value="">Selecciona tu grupo</option>{groups.map(g=><option key={g.id} value={g.id}>{g.nombre}</option>)}</select></label></>}<label>Matrícula<input value={form.matricula} onChange={e=>setForm({...form,matricula:e.target.value})} required/></label><label>Contraseña<input type="password" minLength={6} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label>{authError&&<p className="auth-error">{authError}</p>}<button className="auth-submit" disabled={authBusy}>{authBusy?"Procesando…":authMode==="login"?"Ingresar y recuperar progreso":"Registrar cuenta"}</button></form><button className="auth-switch" onClick={()=>{setAuthMode(authMode==="login"?"register":"login");setAuthError("")}}>{authMode==="login"?"Es mi primera vez · Crear cuenta":"Ya tengo cuenta · Ingresar"}</button></section></div>}
  <section className="hero u1-hero" id="inicio"><div className="hero-copy"><span className="kicker"><i/> Unidad 2 · Ecuaciones e inecuaciones</span><h1>Convierte condiciones en <em>soluciones matemáticas.</em></h1><p>Aprende a resolver ecuaciones, desigualdades y sistemas mediante procedimientos claros y práctica interactiva basada prioritariamente en <em>Matemáticas simplificadas</em>.</p><div className="hero-actions"><a className="primary-btn" href="#temas">Explorar los 4 temas <span>→</span></a></div><div className="hero-notes"><span>✓ Teoría paso a paso</span><span>✓ 5 ejercicios por módulo</span><span>✓ 120 ejercicios por recorrido</span></div></div><div className="algebra-board"><span>UNIDAD 02</span><strong>2x + 5 = 17</strong><div>↓ conserva la igualdad ↓</div><b>x = 6</b><small>De la condición a la solución</small></div></section>
  <section className="section topic-section" id="temas"><div className="section-heading"><div><span className="kicker"><i/> Ruta de aprendizaje</span><h2>Temas de la Unidad II</h2></div><p>Estudia primero el procedimiento y después comprueba lo aprendido.</p></div><div className="topic-cards u2-topics">{topics.map((x,i)=><button key={x.title} className={ti===i?"active":""} onClick={()=>{openTopic(i);setTimeout(()=>document.getElementById("teoria")?.scrollIntoView({behavior:"smooth"}),50)}}><span>{i+1}</span><b>{x.icon}</b><h3>{x.title}</h3><p>{x.short}</p><small>{done.filter(v=>v.startsWith(`${i}-`)).length}/6 actividades</small></button>)}</div></section>
  <section className="u1-learning" id="teoria"><div className="section lesson-layout"><aside><span className="unit-pill">Tema {ti+1} de 4</span><h2>{t.title}</h2><p>{t.short}</p>{topics.map((x,i)=><button key={x.title} className={ti===i?"active":""} onClick={()=>openTopic(i)}><span>{done.filter(v=>v.startsWith(`${i}-`)).length===6?"✓":i+1}</span>{x.title}</button>)}</aside><article className="deep-lesson"><div className="content-label"><span>01</span><div><small>PRIMERO APRENDE</small><strong>Comprende el procedimiento</strong></div></div><h2>{t.title}</h2><div className="lesson-purpose"><div><small>AL TERMINAR PODRÁS</small><p>{t.goal}</p></div><div><small>ANTES DE COMENZAR</small><p>{t.prior}</p></div></div><div className="topic-route">{t.route.map((r,i)=><div key={r}><span>{i+1}</span><strong>{r}</strong></div>)}</div><div className="theory-chapters">{t.blocks.map((b,i)=><section className="theory-chapter" key={b.title}><div className="chapter-number">{String(i+1).padStart(2,"0")}</div><div className="chapter-content"><h3>{b.title}</h3><p><MathText text={b.text}/></p><ul>{b.points.map(p=><li key={p}><MathText text={p}/></li>)}</ul>{b.formula&&<div className="chapter-formula"><small>IDEA CLAVE</small><strong><MathText text={b.formula}/></strong></div>}</div></section>)}</div><div className="examples-heading"><div><small>DE LO SIMPLE A LO COMPLEJO</small><h3>Ejemplos resueltos</h3></div><span>{t.examples.length} ejemplos</span></div><div className="progressive-examples">{t.examples.map((e,i)=><div className="worked-example level-example" key={e.p}><div className="example-level"><small>Nivel {i+1}</small><b>{i+1}/{t.examples.length}</b></div><span>Ejemplo guiado</span><h3><MathText text={e.p}/></h3>{e.steps.map((s,j)=><p key={s}><b>{j+1}</b><MathText text={s}/></p>)}<strong>Resultado: <MathText text={e.r}/></strong></div>)}</div><div className="source-note">Fuente principal de ejercicios: Aguilar Márquez et al., <em>Matemáticas simplificadas</em>, capítulos 6, 8, 12 y 13.</div><a className="to-practice" href="#practica">Ya estudié · Ir a practicar ↓</a></article></div></section>
  <section className="practice-section" id="practica"><div className="section"><div className="practice-intro"><div className="content-label light-label"><span>02</span><div><small>DESPUÉS: PRÁCTICA</small><strong>Laboratorio interactivo</strong></div></div><h2>Práctica: {t.title}</h2><p>Responde cinco ejercicios en cada modalidad y corrobora el bloque completo cuando corresponda.</p></div><div className="practice-box expanded"><div className="activity-head"><div><span>LABORATORIO DEL TEMA {ti+1}</span><h3>Seis módulos interactivos</h3></div><b>{done.filter(v=>v.startsWith(`${ti}-`)).length}/6</b></div><div className="activity-tabs six">{(Object.keys(modules) as ModuleKey[]).map(key=><button key={key} className={`${tab===key?"active ":""}${done.includes(`${ti}-${key}`)?"completed":""}`} onClick={()=>{setTab(key);resetModule()}}><small>{done.includes(`${ti}-${key}`)?"✓ COMPLETADO":`MÓDULO ${modules[key][0]}`}</small><strong>{modules[key][1]}</strong></button>)}</div>{reviewErrors>=5&&<div className="review-reminder"><div><strong>Conviene repasar antes de continuar</strong><p>Has acumulado cinco errores en este módulo. Revisa la explicación y los ejemplos.</p></div><a href="#teoria">Repasar la teoría ↑</a></div>}
   <div className="u2-module"><h3>{modules[tab][1]}</h3>
    {tab==="quick"&&<div className="quick-practice"><small>Ejercicio {quickIndex+1} de 5</small><h4><MathText text={quick[quickIndex].q}/></h4><label>Escribe la solución<input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&checkQuick()} placeholder="Ejemplo: x=4"/></label><button onClick={checkQuick}>Comprobar</button></div>}
    {tab==="quiz"&&<div className="block-list">{quiz.map((q,i)=><fieldset key={q.q}><legend>{i+1}. <MathText text={q.q}/></legend>{shuffle(q.options,ti*31+round*13+i).map(o=><label key={o}><input type="radio" name={`q${i}`} checked={quizAnswers[i]===o} onChange={()=>setQuizAnswers({...quizAnswers,[i]:o})}/><MathText text={o}/></label>)}</fieldset>)}<button onClick={checkQuiz}>Corroborar las cinco respuestas</button></div>}
    {tab==="match"&&<div className="match-list">{pairs.map((p,i)=><label key={p[0]}><strong><MathText text={p[0]}/></strong><select value={matchAnswers[i]||""} onChange={e=>setMatchAnswers({...matchAnswers,[i]:e.target.value})}><option value="">Selecciona la relación</option>{matchOptions.map(o=><option key={o}>{o}</option>)}</select></label>)}<button onClick={checkMatch}>Corroborar relaciones</button></div>}
    {tab==="memory"&&<><p>Encuentra cada expresión o concepto y su pareja correspondiente.</p><div className="memory-grid five">{cards.map((c,i)=><button key={`${c.text}-${i}`} className={opened.includes(i)||matched.includes(c.pair)?"open":""} onClick={()=>flip(i)}>{opened.includes(i)||matched.includes(c.pair)?<MathText text={c.text}/>:"?"}</button>)}</div></>}
    {tab==="sequence"&&<div className="sequence-practice"><small>Procedimiento {seqIndex+1} de 5</small><h4><MathText text={sequences[seqIndex].title}/></h4><div className="selected-steps">{seqPick.map((s,i)=><button key={s} onClick={()=>setSeqPick(seqPick.filter(x=>x!==s))}><span>{i+1}</span>{s}</button>)}</div><div className="available-steps">{shuffle(sequences[seqIndex].steps,ti*41+round*17+seqIndex).filter(s=>!seqPick.includes(s)).map(s=><button key={s} onClick={()=>setSeqPick([...seqPick,s])}>{s}</button>)}</div><button onClick={checkSequence}>Corroborar orden</button></div>}
    {tab==="tf"&&<div className="tf-list">{tfItems.map((q,i)=><fieldset key={q.text}><legend>{i+1}. <MathText text={q.text}/></legend><label><input type="radio" name={`tf${i}`} checked={tfAnswers[i]===true} onChange={()=>setTfAnswers({...tfAnswers,[i]:true})}/>Verdadero</label><label><input type="radio" name={`tf${i}`} checked={tfAnswers[i]===false} onChange={()=>setTfAnswers({...tfAnswers,[i]:false})}/>Falso</label></fieldset>)}<button onClick={checkTf}>Corroborar los cinco enunciados</button></div>}
    {note&&<div className={note.startsWith("¡Correcto")?"module-note success":"module-note error"}>{note}</div>}
   </div></div></div></section>
  <section className="progress-section"><div className="section progress-wrap"><div><span className="kicker light"><i/> Tu avance</span><h2>Domina la Unidad II paso a paso.</h2><p>Completa seis modalidades en cada uno de los cuatro temas.</p></div><div className="progress-card"><div className="ring" style={{"--value":`${progress*3.6}deg`} as React.CSSProperties}><span>{progress}%</span></div><div><strong>{done.length} de 24</strong><p>actividades completadas</p></div></div></div></section>
  <footer><a className="logo" href="#inicio"><img className="logo-image" src="/brand-icon-fm.svg" alt="Monograma FM"/><span>Fundamentos <span>Matemáticos</span></span></a><p>Unidad 2 · Ecuaciones e inecuaciones</p><a href="#inicio">Volver arriba ↑</a></footer>
 </main>
}
