"use client";
/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element, react-hooks/set-state-in-effect */
import {useEffect,useMemo,useState} from "react";

type Student={id:string;matricula:string;nombre:string;activo:boolean;grupo:string;actividades:number;progreso:number;intentos:number;errores:number;refuerzo:string;erroresPorTema:Record<string,number>;historial:number;ultimaActividad:string};
type Data={teacher:{matricula:string;nombre:string;groups:string[]};students:Student[];groups:string[];stats:{alumnos:number;activos:number;promedio:number;errores:number}};
const topicNames=["Ecuaciones de primer grado","Desigualdades lineales","Sistemas de ecuaciones lineales","Ecuaciones de segundo grado"];

export default function Teacher(){
 const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[group,setGroup]=useState("Todos"),[resetting,setResetting]=useState(""),[passwordResetting,setPasswordResetting]=useState(""),[activeTab,setActiveTab]=useState<"students"|"progress"|"difficulties"|"groups">("students");
 async function load(){const r=await fetch("/api/teacher");const d=await r.json();if(r.status===401||r.status===403){window.location.replace("/");return}if(!r.ok)throw new Error(d.error||"No fue posible cargar el panel");setData(d)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const inactivityMs=30*60*1000;const expire=async()=>{await fetch("/api/student",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})});window.alert("La sesión se cerró después de 30 minutos de inactividad.");window.location.replace("/")};const renew=()=>{clearTimeout(timer);timer=setTimeout(()=>{void expire()},inactivityMs)};const events=["pointerdown","pointermove","keydown","scroll","touchstart"] as const;events.forEach(event=>window.addEventListener(event,renew,{passive:true}));renew();return()=>{clearTimeout(timer);events.forEach(event=>window.removeEventListener(event,renew))}},[]);
 const groups=useMemo(()=>["Todos",...Array.from(new Set(data?.groups||[])),...(data?.students.some(x=>x.grupo==="Sin grupo")?["Sin grupo"]:[])],[data]);
 const rows=useMemo(()=>data?.students.filter(x=>(group==="Todos"||x.grupo===group)&&`${x.nombre} ${x.matricula}`.toLowerCase().includes(query.toLowerCase()))||[],[data,group,query]);
 const difficultyRows=useMemo(()=>[...rows].sort((a,b)=>b.errores-a.errores),[rows]);
 const groupRows=useMemo(()=>groups.filter(g=>g!=="Todos").map(nombre=>{const students=data?.students.filter(x=>x.grupo===nombre)||[];return{nombre,students:students.length,progress:students.length?Math.round(students.reduce((a,x)=>a+x.progreso,0)/students.length):0,errors:students.reduce((a,x)=>a+x.errores,0),active:students.filter(x=>x.activo).length}}),[data,groups]);
 function csv(){const head=["Matrícula","Nombre","Grupo","Progreso","Actividades","Respuestas evaluadas","Errores","Estado","Última actividad"],body=rows.map(x=>[x.matricula,x.nombre,x.grupo,`${x.progreso}%`,x.actividades,x.intentos,x.errores,x.activo?"Activa":"Deshabilitada",new Date(x.ultimaActividad).toLocaleString("es-MX")]);const content="\ufeff"+[head,...body].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type:"text/csv;charset=utf-8"}));a.download="seguimiento-fundamentos-matematicos.csv";a.click();URL.revokeObjectURL(a.href)}
 async function resetProgress(student:Student){if(!window.confirm(`Se archivará el intento actual de ${student.nombre} y comenzará uno nuevo desde 0 %. La cuenta y la contraseña se conservarán. ¿Deseas continuar?`))return;setResetting(student.id);const r=await fetch("/api/teacher",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId:student.id})});const d=await r.json();if(!r.ok){setResetting("");return window.alert(d.error||"No fue posible reiniciar el progreso.")}await load();setResetting("");window.alert("El progreso anterior quedó archivado y se abrió un intento nuevo.")}
 async function resetPassword(student:Student){const password=window.prompt(`Escribe una contraseña temporal para ${student.nombre}. Debe tener al menos 8 caracteres.`);if(password===null)return;if(password.length<8)return window.alert("La contraseña temporal debe tener al menos 8 caracteres.");if(!window.confirm(`¿Restablecer la contraseña de ${student.nombre}? La contraseña anterior dejará de funcionar.`))return;setPasswordResetting(student.id);const r=await fetch("/api/teacher",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId:student.id,password})});const d=await r.json();setPasswordResetting("");if(!r.ok)return window.alert(d.error||"No fue posible restablecer la contraseña.");window.alert("Contraseña restablecida. Entrégala al alumno de forma privada.")}
 return <main className="teacher-site">
  <header className="teacher-header"><a className="teacher-brand" href="/"><img src="/brand-icon-fm.svg" alt="Monograma FM"/><span>Fundamentos<strong>Matemáticos</strong></span></a><nav><a href="/">1. Aprendizaje</a><a href="/#practica">2. Módulos interactivos</a><a className="active" href="/docente">Zona Docente</a></nav><a className="teacher-exit" href="/">← Volver al curso</a></header>
  <section className="teacher-hero"><div><span className="teacher-tag">Panel académico · Unidad 2</span><h1>Seguimiento claro para<br/><em>acompañar el aprendizaje.</em></h1><p>Consulta exclusivamente el avance y las dificultades de los grupos que tienes asignados.</p>{data&&<div className="teacher-scope"><b>{data.teacher.nombre}</b><span>{data.teacher.matricula} · Grupos a cargo: {data.teacher.groups.join(", ")||"Sin grupos asignados"}</span></div>}</div><div className="teacher-hero-card"><small>PROGRESO DE TUS GRUPOS</small><strong>{data?.stats.promedio||0}%</strong><div><i style={{width:`${data?.stats.promedio||0}%`}}/></div><span>Promedio de actividades completadas por tus estudiantes</span></div></section>
  <section className="teacher-content">
   <div className="teacher-title"><div><span>CONTROL ACADÉMICO</span><h2>Resumen de tus grupos</h2><p>La información está limitada automáticamente a tus grupos asignados.</p></div><button onClick={csv} disabled={!rows.length}>↓ Exportar CSV</button></div>
   {error?<div className="teacher-message"><h2>No fue posible abrir la Zona Docente</h2><p>{error}</p><a href="/">Regresar al curso</a></div>:!data?<div className="teacher-loading">Preparando el seguimiento académico…</div>:<>
    <div className="stat-grid"><article><span>01</span><small>ALUMNOS REGISTRADOS</small><strong>{data.stats.alumnos}</strong><p>Cuentas creadas</p></article><article><span>02</span><small>CUENTAS ACTIVAS</small><strong>{data.stats.activos}</strong><p>Con acceso disponible</p></article><article className="accent"><span>03</span><small>PROGRESO PROMEDIO</small><strong>{data.stats.promedio}%</strong><p>Unidad 2 · Ecuaciones e inecuaciones</p></article><article><span>04</span><small>ERRORES REGISTRADOS</small><strong>{data.stats.errores}</strong><p>Respuestas incorrectas</p></article></div>
    <div className="teacher-module"><div className="module-tabs"><button className={activeTab==="students"?"active":""} onClick={()=>setActiveTab("students")}>1. Estudiantes</button><button className={activeTab==="progress"?"active":""} onClick={()=>setActiveTab("progress")}>2. Progreso</button><button className={activeTab==="difficulties"?"active":""} onClick={()=>setActiveTab("difficulties")}>3. Dificultades</button><button className={activeTab==="groups"?"active":""} onClick={()=>setActiveTab("groups")}>4. Grupos</button></div>{activeTab!=="groups"&&<div className="table-tools"><label>Buscar estudiante<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre o matrícula"/></label><label>Filtrar por grupo<select value={group} onChange={e=>setGroup(e.target.value)}>{groups.map(g=><option key={g}>{g}</option>)}</select></label><span>{rows.length} resultados</span></div>}
     {activeTab==="students"&&(!rows.length?<div className="empty-students"><b>Sin alumnos registrados todavía</b><p>Cuando un estudiante cree su cuenta, aparecerá automáticamente en este panel.</p></div>:<div className="student-table"><div className="student-row student-head"><span>Estudiante</span><span>Grupo</span><span>Progreso</span><span>Actividad</span><span>Errores</span><span>Estado y acciones</span></div>{rows.map(x=><div className="student-row" key={x.id}><span><b>{x.nombre}</b><small>{x.matricula}</small></span><span>{x.grupo}</span><span><div className="row-progress"><i style={{width:`${x.progreso}%`}}/></div><b>{x.progreso}%</b></span><span><b>{x.actividades}/24</b><small>{x.intentos} respuestas evaluadas · {x.historial} intentos anteriores</small></span><span className={x.errores?"has-errors":""}>{x.errores}</span><span className="student-actions"><span><i className={x.activo?"status-on":"status-off"}/>{x.activo?"Activa":"Deshabilitada"}</span><button disabled={passwordResetting===x.id} onClick={()=>resetPassword(x)}>{passwordResetting===x.id?"Restableciendo…":"Restablecer contraseña"}</button><button disabled={resetting===x.id||(!x.actividades&&!x.intentos&&!x.errores)} onClick={()=>resetProgress(x)}>{resetting===x.id?"Reiniciando…":"Archivar y reiniciar"}</button></span></div>)}</div>)}
     {activeTab==="progress"&&<div className="teacher-view"><div className="view-heading"><span>AVANCE INDIVIDUAL</span><h3>Progreso de actividades</h3><p>Cada estudiante debe completar 24 módulos: seis modalidades en cada uno de los cuatro temas.</p></div><div className="progress-list">{rows.map(x=><article key={x.id}><div><b>{x.nombre}</b><small>{x.matricula} · {x.grupo}</small></div><div className="wide-progress"><i style={{width:`${x.progreso}%`}}/></div><strong>{x.actividades}/24</strong><em>{x.progreso}%</em></article>)}</div></div>}
     {activeTab==="difficulties"&&<div className="teacher-view"><div className="view-heading"><span>SEGUIMIENTO DE RESPUESTAS</span><h3>Dificultades detectadas</h3><p>Se muestran todos los temas en los que el alumno ha cometido errores, ordenados de mayor a menor. El primero es el tema principal para reforzar.</p></div><div className="difficulty-list">{difficultyRows.map(x=>{const rate=x.intentos?Math.round(x.errores/x.intentos*100):0;const topics=Object.entries(x.erroresPorTema||{}).map(([key,value])=>({name:topicNames[Number(key)]||"Tema sin identificar",errors:Number(value)})).filter(item=>item.errors>0).sort((a,b)=>b.errors-a.errors);return <article key={x.id} className={x.errores?"needs-review":""}><div><b>{x.nombre}</b><small>{x.grupo} · {x.intentos} respuestas evaluadas</small>{topics.length?<div className="topic-difficulties">{topics.map((topic,index)=><span className={index===0?"primary-topic":""} key={topic.name}><small>{index===0?"Principal":"También requiere repaso"}</small><b>{topic.name}</b><em>{topic.errors} {topic.errors===1?"error":"errores"}</em></span>)}</div>:<em>Sin dificultad específica registrada</em>}</div><strong>{x.errores}<small>errores</small></strong><span>{rate}% de error</span><p>{x.errores===0?"Sin dificultades registradas":rate>=50?"Requiere acompañamiento":"Conviene reforzar ejercicios"}</p></article>})}</div></div>}
     {activeTab==="groups"&&<div className="teacher-view"><div className="view-heading"><span>COMPARACIÓN POR GRUPO</span><h3>Resumen de grupos</h3><p>Consulta estudiantes, actividad, promedio de avance y errores acumulados.</p></div><div className="group-summary">{groupRows.map(g=><article key={g.nombre}><span>GRUPO</span><h3>{g.nombre}</h3><div><p><b>{g.students}</b> estudiantes</p><p><b>{g.active}</b> activos</p><p><b>{g.progress}%</b> progreso</p><p className={g.errors?"has-errors":""}><b>{g.errors}</b> errores</p></div><div className="wide-progress"><i style={{width:`${g.progress}%`}}/></div></article>)}</div></div>}
    </div>
   </>}
  </section>
 </main>
}
